### ISSUE TITLE
End-Game Conditions?

### ISSUE THREAD

**Issue by kelsicruz** [kamala21/Kamala21#4]
I can't seem to win the game, which is expected, but it resets to a seemingly random game when the end is reached. The AI won, and I tried to pass my last turn, but then the game reset to 3 AI players. Then I was about to beat 2 of the 3 AI's, and the game shut down. Really good GUI though!

**Comment by gannotsk21** [comment]
Also can't rage quit once game is done

**Comment by kelsicruz** [comment]
Game also seems to occasionally play itself...?
