### ISSUE TITLE
AIs Cannot Beat Each Other

### ISSUE THREAD

**Issue by liao21** [kamala21/Kamala21#8]
If user plays all cards (which, to my understanding, should be a victory), the last card played stays on the table and there is no victory prompt. 

One other AI played all of its cards, ending on a 9, but then Simple AI's 3 and 4 appeared to be unable to player with 13 and 12 cards, respectively. If the user presses pass, the text flashes back and forth between P3 and P4. It appears neither AI can play and that they are both passing their turn. 

Cannot reach a victory.

**Comment by kamala21** [comment]
Tried to recreate the game scenario and realized that it would never clear because I forgot to put checks if player(hand) is empty.
